Repository astral-sh/ty, pull requests merged in 2025-07, with the labels that each got.

#745 Drop the README transform and Rust cache from the docs publish workflow
  .github/workflows/publish-docs.yml
Labels: ci

#731 Publish documentation on release
  .github/workflows/release.yml
  dist-workspace.toml
Labels: ci

#729 Copy basic template and styling for documentation from uv
  CONTRIBUTING.md
  docs/.overrides/main.html
  docs/.overrides/partials/integrations/analytics/fathom.html
  docs/index.md
  docs/js/extra.js
  docs/reference/index.md
  docs/requirements-insiders.in
  docs/requirements-insiders.txt
  docs/requirements.in
  docs/requirements.txt
  docs/stylesheets/extra.css
  mkdocs.insiders.yml
  mkdocs.public.yml
  mkdocs.template.yml
Labels: internal

#768 Document `TY_MEMORY_REPORT`
  docs/reference/env.md
Labels: documentation

#917 Improve visibility of copy and line separator in dark mode
  docs/stylesheets/extra.css
Labels: documentation
