Repository astral-sh/ty, pull requests merged in 2025-05, with the labels that each got.

#273 Clean up some path handling in the schemastore script
  scripts/update_schemastore.py
Labels: internal

#277 Update the `uv.lock` on release
  scripts/release.sh
  uv.lock
Labels: internal

#284 Add CLI documentation and update README
  README.md
Labels: documentation

#293 Basic README sections
  README.md
Labels: documentation

#294 docs: Document configuration file discovery
  README.md
Labels: documentation

#295 Document suppressions and exit codes
  README.md
Labels: documentation

#316 Ensure ty runs at latest version
  README.md
Labels: documentation

#327 Add "rules" and "checking a project" sections
  README.md
Labels: documentation

#330 Restore readme transformation script
  .github/workflows/build-binaries.yml
  scripts/transform_readme.py
Labels: internal

#331 Split the documentation out of the top-level README
  .pre-commit-config.yaml
  README.md
  docs/README.md
  docs/reference/cli.md
  docs/reference/configuration.md
  docs/reference/env.md
  docs/reference/rules.md
  scripts/release.sh
Labels: documentation

#334 Update top-level warning
  README.md
Labels: documentation

#333 Include admonitions in the README transform
  scripts/transform_readme.py
Labels: internal

#329 Rewrite the getting started documentation
  README.md
  docs/README.md
Labels: documentation

#335 Edit the module and editor sections of the docs
  docs/README.md
Labels: documentation

#337 Edit the rule level and suppression comment sections
  docs/README.md
Labels: documentation

#340 Fix typo
  README.md
Labels: documentation

#341 fix link to CLI docs
  docs/README.md
Labels: documentation

#342 Fix link to configuration reference page
  docs/README.md
Labels: documentation

#345 Rule levels: minor wording suggestion
  docs/README.md
Labels: documentation

#344 Minor clarifications in Python version docs
  docs/README.md
Labels: documentation

#343 Add reference for editor settings
  .pre-commit-config.yaml
  docs/README.md
  docs/reference/editor-settings.md
  docs/reference/env.md
Labels: documentation

#348 Contributing guide: clarifications and link
  CONTRIBUTING.md
Labels: documentation

#349 Correctly indent the list in the "Relasing ty" section
  CONTRIBUTING.md
Labels: documentation

#352 Update rooster
  pyproject.toml
  uv.lock
Labels: release

#353 Setup basic grouping for changelog
  pyproject.toml
Labels: release

#357 Bump rooster
  pyproject.toml
  uv.lock
Labels: internal

#360 Use `ty server` instead of `ty lsp`
  CONTRIBUTING.md
Labels: documentation

#361 Fix repository in README transform script
  scripts/transform_readme.py
Labels: release

#415 [CI] Add check for changes in autogenerated files
  .gitattributes
  .github/workflows/ci.yaml
  scripts/autogenerate_files.sh
  scripts/release.sh
Labels: ci

#432 Add: README badges
  README.md
Labels: documentation

#446 Issue template: link to frequently encountered problems
  .github/ISSUE_TEMPLATE/1_bug_report.yaml
Labels: internal

#440 Add link to playground to README.md
  README.md
Labels: documentation

#486 Fix anchor tag in `README` ToC
  docs/README.md
Labels: documentation

#490 Contributor guide: document sources of autogenerated reference docs
  CONTRIBUTING.md
Labels: documentation
